export const trafficColumns = [
  { key: "selection", label: "", color: '#ffffff', fixed: true, width: 34, left: 0, sortable: false, align: "left", hideable: false },
  { key: "name", label: "Название", color: '#fffedc', fixed: true, width: 510, left: 34, sortable: true, align: "left", hideable: false },
  { key: "offer_id", label: "Поток", color: '#fffedc', fixed: true, width: 140, left: 544, sortable: true, align: "left", hideable: false },
  { key: "buyer_id", label: "Баер", color: '#fffedc', fixed: true, width: 50, left: 684, sortable: true, align: "left", hideable: false },
  { key: "offer_type", label: "Тип заказа", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "site_type", label: "Посадочная", color: '#fffedc', sortable: true, align: "left", hideable: false },
  { key: "status", label: "Статус", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "marks", label: "Метки", color: '#fffedc', sortable: false, align: "center", hideable: true },
  { key: "flow_type", label: "Тип", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "column", label: "Колонка", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "inventory.quantity", label: "Остатки", color:'#fffedc', sortable: true, align: "left", hideable: true },
  { key: "first.all_count", label: "Заказы", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "first.clean_count", label: "Чистые", color: '#fffedc', sortable: true, align: "left", hideable: true },
  { key: "first.approves_count", label: "Апрувы", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.trash_percentage", label: "% треша", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.approves_percentage", label: "% апрува", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.unprocessed_percentage", label: "% необр. лиды", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.approves_median", label: "Сред. чек", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.preorder_percentage", label: "% предзаказа", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.completed_percentage", label: "% выкуп", color: '#dcffdc', sortable: true, align: "left", hideable: true },
  { key: "first.cr_percentage", label: "% CR", color: '#ffead4', sortable: true, align: "left", hideable: true },
  { key: "first.spend", label: "Спенд", color: '#d4ecff', sortable: true, align: "left", hideable: true },
  { key: "first.conversion", label: "Конверсия", color: '#d4ecff', sortable: true, align: "left", hideable: true },
  { key: "first.lead_price", label: "За лид", color: '#d4ecff', sortable: true, align: "left", hideable: true },
  { key: "campaigns", label: "Актив.", color: '#d4ecff', sortable: true, align: "left", hideable: true },
  { key: "first.usd_median", label: "Сред. чек $", color: '#ecdcff', sortable: true, align: "right", hideable: true  },
];
