# Generated by Django 4.2.30 on 2026-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
