export const tagsColumns = [
  { key: "medium", label: "Канал", color: '#fffedc', fixed: true, width: 120, left: 0, sortable: true, align: "left" },
  { key: "campaign", label: "Кампания", color: '#fffedc', fixed: true, width: 200, left: 120, sortable: true, align: "left" },
  { key: "content", label: "Содержание", color: '#fffedc', fixed: true, width: 200, left: 320, sortable: true, align: "left" },
  { key: "keyword", label: "Слово", color: '#fffedc', fixed: true, width: 200, left: 520, sortable: true, align: "left" },
  { key: "status", label: "Статус", color: '#fffedc', sortable: true, align: "left" },
  { key: "orders", label: "Заказы", color: '#fffedc', sortable: true, align: "left" },
  { key: "clean_orders", label: "Чистые", color: '#fffedc', sortable: true, align: "left" },
  { key: "approves", label: "Апрувы", color: '#dcffdc', sortable: true, align: "left" },
  { key: "percent_trash", label: "% треша", color: '#dcffdc', sortable: true, align: "left" },
  { key: "percent_approve", label: "% апрува", color: '#dcffdc', sortable: true, align: "left" },
  { key: "percent_unprocessed", label: "% необр. лиды", color: '#dcffdc', sortable: true, align: "left" },
  { key: "avg_price", label: "Сред. чек", color: '#dcffdc', sortable: true, align: "left" },
  { key: "percent_preorder", label: "% предзаказа", color: '#dcffdc', sortable: true, align: "left" },
  { key: "percent_completed", label: "% выкуп", color: '#dcffdc', sortable: true, align: "left" },
  { key: "spend", label: "Спенд", color: '#d4ecff', sortable: true, align: "left" },
  { key: "conversion", label: "Конверсия", color: '#d4ecff', sortable: true, align: "left" },
  { key: "lead_price", label: "За лид", color: '#d4ecff', sortable: true, align: "left" },
  { key: "usd_median", label: "Сред. чек", color: '#ecdcff', sortable: true, align: "right" },
];
